{
 "title": "Detalles de indice",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Schema",
    "label": "Proyecto",
    "query": "SELECT\n\tschema_name\nFROM\n\tinformation_schema.schemata\nWHERE\n\tschema_name !~ '^(pg_)' AND\n\tschema_name != 'information_schema' AND\n\tschema_name != 'topology' AND\n\tschema_name != 'cron'\n"
   },
   {
    "name": "Year",
    "label": "Año",
    "query": "select distinct(\"año\")::integer from \"${Schema}\".\"${Index}\""
   },
   {
    "name": "Index",
    "label": "Indice",
    "query": "SELECT\n\t table_name\nFROM\n\tinformation_schema.tables\nWHERE\n\ttable_schema = '${Schema}' AND\n\ttable_type = 'BASE TABLE' AND\n        table_name ~ '^(0|1|A|B|Theme)'\n"
   },
   {
    "name": "index_title",
    "query": "select display_name from indexes_metadata where index_table_name = '${Index}'"
   },
   {
    "name": "index_description",
    "query": "select description from indexes_metadata where index_table_name = '${Index}'"
   },
   {
    "name": "index_formula",
    "query": "select formula from indexes_metadata where index_table_name = '${Index}'"
   },
   {
    "name": "index_classes",
    "query": "select classes from indexes_metadata where index_table_name = '${Index}'"
   },
   {
    "name": "index_metric",
    "query": "select metric_column from indexes_metadata where index_table_name = '${Index}'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "content": "\n# <p style=\"text-align: center;\"> ${index_title} </p>\n\n## <p style=\"text-align: center;\"> ${index_description} </p>\n\n________\n\n### <p style=\"text-align: center;\">  ${index_formula} </p>\n",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Legend",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select * from json_to_recordset(\n  '${index_classes}'\n) as t(low float, high float, value text, color text) order by low\n\n"
    }
   ]
  },
  {
   "title": "${index_metric} - ${Year}",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \"${index_metric}\" from \"${Schema}\".\"${Index}\"  where \"año\"=${Year}\n"
    }
   ]
  },
  {
   "title": "Tendencia",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TO_TIMESTAMP(\"año\"::text, 'YYYY') as \"time\",\n  \"${index_metric}\"\nFROM \"${Index}\"\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Datos completos",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select * from \"${Schema}\".\"${Index}\"\n"
    }
   ]
  }
 ]
}