{
 "title": "Sunburst de indices",
 "time": { "from": "2005-01-01T00:00:00.000Z", "to": "2018-01-01T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "YEAR_COLUMN", "query": "año" },
   {
    "name": "SCHEMA",
    "label": "Proyecto",
    "query": "SELECT\n\tschema_name\nFROM\n\tinformation_schema.schemata\nWHERE\n\tschema_name !~ '^(pg_)' AND\n\tschema_name != 'information_schema' AND\n\tschema_name != 'topology' AND\n\tschema_name != 'cron'\n"
   },
   {
    "name": "YEAR",
    "label": "Año",
    "query": "SELECT distinct(\"${YEAR_COLUMN}\")::integer FROM \"${SCHEMA}\".\"${INDEX_TABLE}\""
   },
   {
    "name": "INDEX_TABLES",
    "label": "Indice",
    "query": "SELECT\n\t table_name\nFROM\n\tinformation_schema.tables\nWHERE\n\ttable_schema = '${SCHEMA}' AND\n\ttable_type = 'BASE TABLE' AND\n        table_name ~ '^(0|1|A|B|Theme)'\n"
   },
   {
    "name": "INDEX",
    "query": "SELECT display_name FROM \"${SCHEMA}\".indexes_metadata"
   },
   {
    "name": "INDEX_TABLE",
    "query": "SELECT index_table_name \nFROM \"${SCHEMA}\".indexes_metadata\nWHERE display_name='${INDEX}'"
   },
   {
    "name": "INDEX_METRIC",
    "query": "SELECT metric_column\nFROM \"${SCHEMA}\".indexes_metadata\nWHERE display_name='${INDEX}'"
   },
   {
    "name": "INDEXES_SUNBURST",
    "query": "SELECT json\nFROM indexes_sunburst \nWHERE tstzrange(\"min_date\", \"max_date\", '[)') && '[\"${YEAR}-01-01 00:00:00+00\",\"${YEAR}-12-31 23:59:59+00\"]'::tstzrange ;"
   },
   { "name": "SELECTED_NODE", "query": "none_for_now" },
   {
    "name": "INDEX_DESCRIPTION",
    "query": "SELECT description\nFROM \"${SCHEMA}\".indexes_metadata\nWHERE display_name='${INDEX}'"
   },
   {
    "name": "INDEX_FORMULA",
    "query": "SELECT formula\nFROM \"${SCHEMA}\".indexes_metadata\nWHERE display_name='${INDEX}'"
   },
   {
    "name": "INDEX_CLASSES",
    "query": "SELECT classes::json->'classes'\nFROM \"${SCHEMA}\".indexes_metadata\nWHERE display_name='${INDEX}'"
   },
   {
    "name": "METRIC_VALUE",
    "query": "SELECT \"${INDEX_METRIC}\" FROM \"${SCHEMA}\".\"${INDEX_TABLE}\" where \"${YEAR_COLUMN}\"=${YEAR}"
   },
   {
    "name": "METRIC_VALUES",
    "query": "SELECT \"${INDEX_METRIC}\" FROM \"${SCHEMA}\".\"${INDEX_TABLE}\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "\n# <p style=\"text-align: center;\"> ${INDEX} </p>\n\n## <p style=\"text-align: center;\"> ${INDEX_DESCRIPTION} </p>\n\n________\n\n### <p style=\"text-align: center;\">  ${INDEX_FORMULA} </p>\n"
   },
   "content": "\n# <p style=\"text-align: center;\"> ${index_title} </p>\n\n## <p style=\"text-align: center;\"> ${index_description} </p>\n\n________\n\n### <p style=\"text-align: center;\">  ${index_formula} </p>\n",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "luipir-table-panel",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM json_to_recordset(\n  '${INDEX_CLASSES}'\n) as t(low float, high float, value text, color text) order by low\n\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "luipir-worldmap-panel",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT qgis_project_options\nFROM \"${SCHEMA}\".indexes_metadata\nWHERE display_name='${INDEX}'"
    }
   ]
  },
  {
   "title": "Año ${YEAR}",
   "type": "luipir-sunburst-panel",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_TIMESTAMP(\"año\"::text, 'YYYY') as \"time\",\n  \"02_evaluation\" as \"a_metric\"\nFROM \"Theme 1 synthesis\"\nWHERE ${Interval}::integer = \"año\"::integer\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "${INDEX} - ${YEAR}",
   "type": "luipir-gauge-panel",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"${INDEX_METRIC}\"\nFROM \"${SCHEMA}\".\"${INDEX_TABLE}\"\nWHERE \"${YEAR_COLUMN}\"=${YEAR}\n"
    }
   ]
  },
  {
   "title": "Time series of: ${INDEX}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TO_TIMESTAMP(\"${YEAR_COLUMN}\"::text, 'YYYY') as \"time\",\n  \"${INDEX_METRIC}\"\nFROM \"${INDEX_TABLE}\"\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Raw data of: ${INDEX}",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \"${YEAR_COLUMN}\", \"${INDEX_METRIC}\", *\nFROM \"${SCHEMA}\".\"${INDEX_TABLE}\"\nORDER BY \"${YEAR_COLUMN}\" DESC\n"
    }
   ]
  }
 ]
}